### ISSUE TITLE
PETSc 3.5.2 fails on Darwin - duplicate symbols

### ISSUE THREAD

**Issue by johannesring** [hashdist/hashstack#517]
I am getting the following error on Darwin when building `petsc` after the upgrade to 3.5.2:

```
[petsc]      CLINKER /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libpetsc.3.5.2.dylib
[petsc] duplicate symbol _mc64bd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64wd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64rd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64sd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64dd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64ed_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64fd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64ud_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] duplicate symbol _mc64qd_ in:
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_dist_3.3.a(mc64ad.o)
[petsc]     /Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libsuperlu_4.3.a(mc64ad.o)
[petsc] ld: 9 duplicate symbols for architecture x86_64
[petsc] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[petsc] make[2]: *** [/Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re/arch-darwin-c-debug/lib/libpetsc.3.5.2.dylib] Error 1
[petsc] make[2]: Leaving directory `/Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re'
[petsc] make[1]: *** [gnumake] Error 2
[petsc] make[1]: Leaving directory `/Users/johannr/.hashdist/tmp/petsc-vjfeuuvbb6re'
[petsc] **************************ERROR*************************************
[petsc]   Error during compile, check arch-darwin-c-debug/conf/make.log
[petsc]   Send it and arch-darwin-c-debug/conf/configure.log to petsc-maint@mcs.anl.gov
[petsc] ********************************************************************
[petsc] make: *** [all] Error 1
[petsc|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
[petsc|ERROR] command failed (code=2); raising
```

I am using the following in my profile to build `petsc`:

```
  petsc:
    build_with: |
      parmetis, scotch, suitesparse
    download: |
      superlu, superlu_dist
    coptflags: -O2
    link: shared
    debug: false
    disable_fortran: true
```
