### ISSUE TITLE
mshr fails to build on ubuntu 12.04

### ISSUE THREAD

**Issue by JaroslavHron** [hashdist/hashstack#603]
here is the tail of the build log with the error

```
2015/01/12 12:23:43 - INFO: [package:run_job] [ 73%] Building CXX object CMakeFiles/mshr.dir/src/SurfaceConsistency.cpp.o
2015/01/12 12:23:44 - INFO: [package:run_job] [ 76%] Building CXX object CMakeFiles/mshr.dir/src/CSGPrimitives3D.cpp.o
2015/01/12 12:23:44 - INFO: [package:run_job] /srv/nobackup/hron/HASH/tmp/mshr-puz7sejpsfd6-1/src/CSGPrimitives3D.cpp: In constructor 'mshr::Box::Box(double, double, double, double, double, double)':
2015/01/12 12:23:44 - INFO: [package:run_job] /srv/nobackup/hron/HASH/tmp/mshr-puz7sejpsfd6-1/src/CSGPrimitives3D.cpp:87:5: error: type 'mshr::Box' is not a direct base of 'mshr::Box'
2015/01/12 12:23:44 - INFO: [package:run_job] make[2]: *** [CMakeFiles/mshr.dir/src/CSGPrimitives3D.cpp.o] Error 1
2015/01/12 12:23:44 - INFO: [package:run_job] make[1]: *** [CMakeFiles/mshr.dir/all] Error 2
2015/01/12 12:23:44 - INFO: [package:run_job] make: *** [all] Error 2
2015/01/12 12:23:44 - ERROR: [package:run_job] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
2015/01/12 12:23:44 - ERROR: [package:run_job] command failed (code=2); raising
```

**Comment by certik** [comment]
What compiler do you have?

**Comment by JaroslavHron** [comment]
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-werror --with-arch-32=i686 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 
```

**Comment by johannesring** [comment]
I ran into the same problem when compiling `mshr` on Ubuntu precise (`gcc` version 4.6.3). I have reported the problem [here](https://bitbucket.org/benjamik/mshr/issue/21/mshr-fails-to-build-on-ubuntu-precise).

**Comment by johannesring** [comment]
Fixed in #604.
