### PR TITLE
Upgrade OpenMPI to latest stable version 1.8.4.

### PR DESCRIPTION
**Pull request by johannesring**
The current version of OpenMPI in HashStack is old and it would be good to upgrade to the latest stable version.

### CODE REVIEW

**Comment by johannesring** [comment]
I got the below error when building `petsc`, so we might hold on before merging this:

    2015/02/04 10:28:49 - INFO: [package:run_job] *******************************************************************************
    2015/02/04 10:28:49 - INFO: [package:run_job]          UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
    2015/02/04 10:28:49 - INFO: [package:run_job] -------------------------------------------------------------------------------
    2015/02/04 10:28:49 - INFO: [package:run_job] Fortran compiler you provided with -FC=/home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90 does not work.
    2015/02/04 10:28:49 - INFO: [package:run_job] Cannot compile/link FC with /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90.
    2015/02/04 10:28:49 - INFO: [package:run_job] *******************************************************************************

**Comment by ahmadia** [comment]
Huh.  What system is this a problem on?

**Comment by johannesring** [comment]
It is on my laptop which is running Debian unstable.

**Comment by ahmadia** [comment]
@jedbrown - Have you seen this on the PETSc maintenance list?  We're using PETSc 3.5.2 and getting an error against OpenMPI 1.8.4's Fortran compiler script.

**Comment by jedbrown** [comment]
Always `configure.log`.  Looks like something is wrong with the compiler or linker, but we'll never know what without `configure.log`.

**Comment by ahmadia** [comment]
Yeah, that was the next step :)  @johannesring - feel free to direct this either to petsc-maint (with configure.log) or push the file up on a pastebin where I can look at it.

**Comment by johannesring** [comment]
@ahmadia - yes I will do that as soon I'm back at my computer (in a few hours).

**Comment by johannesring** [comment]
The `configure.log` is now available [here](https://gist.github.com/johannesring/ac19313fe7ce183fce42). It looks like this is the relevant part:

    Executing: /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90  -o /home/johannr/.hashdist/tmp/petsc-rs4zootsnzgx/_tmp/petsc-wEruKn/config.setCompilers/conftest    /home/johannr/.hashdist/tmp/petsc-rs4zootsnzgx/_tmp/petsc-wEruKn/config.setCompilers/conftest.o 
    Possible ERROR while running linker: exit code 256
    stderr:
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_test_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_request_get_status_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_dist_graph_create_adjacent_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_dist_graph_neighbors_count_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_initialized_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_get_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_intercomm_merge_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_op_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_comm_test_inter_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_dist_graph_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_map_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_testsome_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_type_get_attr_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_sub_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_iprobe_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_info_get_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_op_commutative_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_testall_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_improbe_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_test_cancelled_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_win_test_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_file_get_atomicity_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_file_set_atomicity_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_win_get_attr_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_status_set_cancelled_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_finalized_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_is_thread_main_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_info_get_valuelen_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_graph_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_testany_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_comm_get_attr_'
    collect2: error: ld returned 1 exit status
                Popping language FC
            Error testing Fortran compiler: Cannot compile/link FC with /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90.
             MPI installation /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90 is likely incorrect.
      Use --with-mpi-dir to indicate an alternate MPI.
              Deleting "FC"

**Comment by ahmadia** [comment]
Does the mpif90 compiler work from the command line?  Do you need it for this machine?  Looks like the OpenMPI build is broken for your system.  The PMPI symbols are weak references that should resolve to the MPI symbols.

**Comment by johannesring** [comment]
No, it doesn't work:

    johannr@debian-t420s:tmp$ /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90 -c -o conftest.o conftest.F
    johannr@debian-t420s:tmp$ /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/bin/mpif90 -o conftest conftest.o
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_test_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_request_get_status_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_dist_graph_create_adjacent_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_dist_graph_neighbors_count_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_initialized_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_get_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_intercomm_merge_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_op_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_comm_test_inter_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_dist_graph_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_map_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_testsome_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_type_get_attr_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_cart_sub_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_iprobe_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_info_get_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_op_commutative_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_testall_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_improbe_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_test_cancelled_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_win_test_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_file_get_atomicity_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_file_set_atomicity_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_win_get_attr_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_status_set_cancelled_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_finalized_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_is_thread_main_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_info_get_valuelen_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_graph_create_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_testany_'
    /home/johannr/.hashdist/bld/mpi/uetoce5mbue4/lib/libmpi_usempif08.so: undefined reference to `pmpi_comm_get_attr_'
    collect2: error: ld returned 1 exit status

But the system `mpif90` works:

    johannr@debian-t420s:tmp$ mpif90 -c -o conftest.o conftest.F
    johannr@debian-t420s:tmp$ mpif90 -o conftest conftest.o
    johannr@debian-t420s:tmp$ 

The `conftest.F` was copied from PETSc and looks like this:

             program main

             end

I'm looking into swithing to MPICH but it would also be good to get OpenMPI 1.8.4 working.

**Comment by ahmadia** [comment]
@johannesring - What would you like to do with this one?

**Comment by johannesring** [comment]
I would like to try on a different machine to see if I can reproduce the error there. I will do that tomorrow.

**Comment by johannesring** [comment]
I could reprodcue the problem on a different machine with Debian unstable, however it worked fine on a machine with Ubuntu 14.04. I guess it is a problem with the mpif90 compiler on Debian unstable. I'm fine with merging this now but it is not important to me since I have switched to MPICH.
